# Data frame preparation

In [8]:
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
df = pd.read_csv('../data/unprocessed/Foodpanda Analysis Dataset.csv')

In [5]:
df.describe()

          quantity        price  order_frequency  loyalty_points       rating
count  6000.000000  6000.000000      6000.000000     6000.000000  4032.000000
mean      2.991667   800.524880        25.304667      250.173667     3.012153
std       1.414778   404.855029        14.358930      144.608478     1.411615
min       1.000000   100.300000         1.000000        0.000000     1.000000
25%       2.000000   441.997500        13.000000      125.000000     2.000000
50%       3.000000   806.460000        25.000000      249.500000     3.000000
75%       4.000000  1149.737500        37.000000      378.000000     4.000000
max       5.000000  1499.950000        50.000000      500.000000     5.000000

In [23]:
df.head(9)

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,C5663,Male,Adult,Peshawar,1/14/2024,O9663,8/23/2023,McDonald's,Burger,Italian,5,1478.27,Cash,38,7/19/2025,238,Active,NaN,10/14/2024,Cancelled
1,C2831,Male,Adult,Multan,7/7/2024,O6831,8/23/2023,KFC,Burger,Italian,3,956.04,Wallet,24,11/25/2024,81,Active,2.0,8/21/2025,Delayed
2,C2851,Other,Senior,Multan,6/20/2025,O6851,8/23/2023,Pizza Hut,Fries,Italian,2,882.51,Cash,42,5/10/2025,82,Inactive,3.0,9/19/2024,Delayed
3,C1694,Female,Senior,Peshawar,9/5/2023,O5694,8/23/2023,Subway,Pizza,Dessert,4,231.30,Card,27,7/24/2025,45,Inactive,2.0,6/29/2025,Delayed
4,C4339,Other,Senior,Lahore,12/29/2023,O8339,8/24/2023,KFC,Sandwich,Dessert,1,1156.69,Cash,35,12/21/2024,418,Inactive,NaN,3/6/2025,Cancelled
5,C6543,Other,Adult,Karachi,9/28/2023,O10543,8/24/2023,Burger King,Pizza,Fast Food,5,1213.62,Cash,45,10/10/2024,418,Inactive,4.0,6/1/2025,Delivered
6,C6423,Male,Adult,Lahore,4/8/2025,O10423,8/24/2023,McDonald's,Pasta,Continental,5,672.91,Wallet,31,5/25/2025,347,Active,NaN,3/4/2025,Cancelled
7,C4621,Male,Adult,Peshawar,2/5/2024,O8621,8/24/2023,Pizza Hut,Pizza,Chinese,2,271.74,Cash,14,5/1/2025,429,Active,2.0,9/30/2024,Delivered
8,C5146,Other,Senior,Karachi,12/17/2024,O9146,8/24/2023,KFC,Pizza,Dessert,5,596.96,Wallet,1,5/16/2025,24,Active,4.0,10/27/2024,Delayed

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      6000 non-null   object
 1   gender           6000 non-null   object
 2   age              6000 non-null   object
 3   city             6000 non-null   object
 4   signup_date      6000 non-null   object
 5   order_id         6000 non-null   object
 6   order_date       6000 non-null   object
 7   restaurant_name  6000 non-null   object
 8   dish_name        6000 non-null   object
 9   category         6000 non-null   object
 10  quantity         6000 non-null   int64
 11  price            6000 non-null   float64
 12  payment_method   6000 non-null   object
 13  order_frequency  6000 non-null   int64
 14  last_order_date  6000 non-null   object
 15  loyalty_points   6000 non-null   int64
 16  churned          6000 non-null   object
 17  rating           4032 non-null   float64
 18  rating_date      6000 non-null   object
 19  delivery_status  6000 non-null   object
dtypes: float64(2), int64(3), object(15)
memory usage: 937.6+ KB

In [9]:
df.shape

(6000, 20)

In [25]:
missing_percentage = pd.DataFrame((df.isnull().sum()/len(df))*100).reset_index()
missing_percentage.columns = ["variables", "missing_percentage"]
missing_percentage

          variables  missing_percentage
0       customer_id                 0.0
1            gender                 0.0
2               age                 0.0
3              city                 0.0
4       signup_date                 0.0
5          order_id                 0.0
6        order_date                 0.0
7   restaurant_name                 0.0
8         dish_name                 0.0
9          category                 0.0
10         quantity                 0.0
11            price                 0.0
12   payment_method                 0.0
13  order_frequency                 0.0
14  last_order_date                 0.0
15   loyalty_points                 0.0
16          churned                 0.0
17           rating                 0.0
18      rating_date                 0.0
19  delivery_status                 0.0

In [20]:
print(f"Total missing ratings: {df['rating'].isnull().sum()}")

Total missing ratings: 1968

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.columns

Index(['customer_id', 'gender', 'age', 'city', 'signup_date', 'order_id',
       'order_date', 'restaurant_name', 'dish_name', 'category', 'quantity',
       'price', 'payment_method', 'order_frequency', 'last_order_date',
       'loyalty_points', 'churned', 'rating', 'rating_date',
       'delivery_status'],
      dtype='object')

In [24]:
df['rating'].fillna(df['rating'].mean(), inplace=True)

# Export Data

In [27]:
import pickle
df.to_pickle('../data/processed/preprocessed.pkl')