# Data Inspection

In [328]:
import pandas as pd
import numpy as np

In [329]:
df = pd.read_pickle('../data/processed/train.pkl')

In [330]:
df.head(5)

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
3897,C5652,Female,Teenager,Multan,4/16/2024,O9652,2024-12-07,Burger King,Fries,Fast Food,2,554.07,Cash,4,2025-07-25,242,Active,3.012153,10/12/2024,Cancelled
5628,C2031,Other,Teenager,Islamabad,3/15/2025,O6031,2024-12-16,McDonald's,Fries,Dessert,1,1001.93,Card,16,2025-07-08,426,Active,4.000000,12/15/2024,Delivered
1756,C4096,Male,Teenager,Lahore,6/8/2024,O8096,2024-03-23,Subway,Fries,Dessert,2,649.95,Cash,24,2025-04-21,125,Inactive,3.012153,2/12/2025,Cancelled
2346,C3933,Other,Adult,Karachi,7/18/2024,O7933,2024-06-06,McDonald's,Sandwich,Continental,5,300.25,Cash,42,2025-06-20,190,Inactive,3.000000,7/7/2025,Delivered
2996,C1335,Male,Adult,Peshawar,5/11/2024,O5335,2024-08-21,Pizza Hut,Fries,Dessert,2,1363.64,Cash,2,2025-06-10,385,Inactive,3.012153,4/13/2025,Cancelled

# Feature Aggregation

In [331]:
df['order_timespan_days'] = (df['last_order_date'] - df['order_date']).dt.days

In [332]:
df['order_quantity'] = (df['quantity'] * df['order_frequency'])

# Unused feature removal

# df1

In [333]:
df1 = df[['rating','delivery_status','churned']]

In [334]:
delivery_dummies = pd.get_dummies(df1['delivery_status'], dtype=int)

df_encoded = df1.join(delivery_dummies)

df_encoded = df_encoded.drop('delivery_status', axis=1)

In [ ]:
df_encoded.shape

(4800, 5)

# df2

In [336]:
#Creating another df with different features/added features
df2 = df[['restaurant_name','churned','quantity','loyalty_points','city','age','gender','order_frequency','price','rating']]

In [337]:
restaurant_dummies = pd.get_dummies(df2['restaurant_name'], dtype=int)
city_dummies = pd.get_dummies(df2['city'], dtype=int)
gender_dummies = pd.get_dummies(df2['gender'], dtype=int)
 
df2_encoded = df2.join(restaurant_dummies).join(city_dummies).join(gender_dummies)
df2_encoded = df2_encoded.drop(['restaurant_name','city','gender'], axis=1)

# Final Feature Inspection

In [338]:
df2_encoded.head(5)

,churned,quantity,loyalty_points,age,order_frequency,price,rating,Burger King,KFC,McDonald's,Pizza Hut,Subway,Islamabad,Karachi,Lahore,Multan,Peshawar,Female,Male,Other
3897,Active,2,242,Teenager,4,554.07,3.012153,1,0,0,0,0,0,0,0,1,0,1,0,0
5628,Active,1,426,Teenager,16,1001.93,4.000000,0,0,1,0,0,1,0,0,0,0,0,0,1
1756,Inactive,2,125,Teenager,24,649.95,3.012153,0,0,0,0,1,0,0,1,0,0,0,1,0
2346,Inactive,5,190,Adult,42,300.25,3.000000,0,0,1,0,0,0,1,0,0,0,0,0,1
2996,Inactive,2,385,Adult,2,1363.64,3.012153,0,0,0,1,0,0,0,0,0,1,0,1,0

In [339]:
df2_encoded.columns

Index(['churned', 'quantity', 'loyalty_points', 'age', 'order_frequency',
       'price', 'rating', 'Burger King', 'KFC', 'McDonald's', 'Pizza Hut',
       'Subway', 'Islamabad', 'Karachi', 'Lahore', 'Multan', 'Peshawar',
       'Female', 'Male', 'Other'],
      dtype='object')

# Export Data

In [340]:
import pickle
df_encoded.to_pickle('../data/processed/ft_engineered.pkl')

In [343]:
df2_encoded.to_pickle('../data/processed/ft_engineered2.pkl')